### ISSUE TITLE
Create Dataset Class for multiple basins

### ISSUE THREAD

**Issue by soelemaafnan** [NWC-CUAHSI-Summer-Institute/dCFE#10]

**Comment by RY4GIT** [comment]
@soelemaafnan is coding the Data class on the branch `dataloader` to read static attributes from `n` number of CAMELS basins 
https://github.com/NWC-CUAHSI-Summer-Institute/dCFE/blob/dataloader/src/data/Data.py

### Done so far 
- `get_forcings`, `get_observations`, and `get_attributes`

### Needs to be done 
- [ ] `__getitem__` needs debugging
- [ ] `get_cfe_params` needs to be rewritten in [ParameterList](https://pytorch.org/docs/stable/generated/torch.nn.ParameterList.html)
- [ ] Make sure n-by-1 torch tensor attributes & parameters can be correctly passed and read in `cfe_py` and `bmi_cfe`

### Note on GIUH
We haven't figured out a way to deal with GIUH, whose length varies by basins

**Comment by RY4GIT** [comment]
Merged dataloader branch and started working on the branch dataloader-ryoko

**Comment by RY4GIT** [comment]
Addressed in f828afb77af59fcd9401019f3f82583855904a60
